Repository ojasaklechayt/Oju-s-Blogs, pull requests merged in 2023-10, with the labels that each got.

#4 update CONTRIBUTION.md
  CONTRIBUTING.md
Labels: documentation, hacktoberfest-accepted

#6 📝 Updated the Contribution.MD 📝
  CONTRIBUTING.md
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted

#14 Improved UI
  Backend/.gitignore
  Frontend/frontend/.gitignore
  Frontend/frontend/src/components/AddBlog.js
  Frontend/frontend/src/components/Auth.js
  Frontend/frontend/src/components/Blog.js
  Frontend/frontend/src/components/BlogDetail.js
  Frontend/frontend/src/components/Header.js
  Frontend/frontend/src/components/LandingPage.js
Labels: hacktoberfest, hacktoberfest-accepted

#21 Added react_Toastify to display messages issue #9
  Frontend/frontend/package-lock.json
  Frontend/frontend/package.json
  Frontend/frontend/src/components/Auth.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#25 Add: Validation for imageURL
  Frontend/frontend/src/components/AddBlog.js
  Frontend/frontend/src/components/LandingPage.js
Labels: hacktoberfest, hacktoberfest-accepted

#19 footer added
  Frontend/frontend/src/App.js
  Frontend/frontend/src/Footer.jsx
  Frontend/frontend/src/index.css
  Frontend/package-lock.json
  package-lock.json
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#27 Added back to top button!
  Frontend/frontend/package-lock.json
  Frontend/frontend/package.json
  Frontend/frontend/src/App.js
  Frontend/frontend/src/components/BackToTop.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#23 [login / Signup] Add validations
  Frontend/frontend/src/components/Auth.js
Labels: hacktoberfest, hacktoberfest-accepted

#24 feat:Added the image upload functionality
  Frontend/frontend/src/components/AddBlog.js
Labels: hacktoberfest, hacktoberfest-accepted

#34 created a single js file for all api calls
  Backend/app.js
  Frontend/frontend/src/API/API.js
  Frontend/frontend/src/components/AddBlog.js
  Frontend/frontend/src/components/Auth.js
  Frontend/frontend/src/components/Blog.js
  Frontend/frontend/src/components/BlogDetail.js
  Frontend/frontend/src/components/Blogs.js
  Frontend/frontend/src/components/UserBlogs.js
Labels: hacktoberfest, hacktoberfest-accepted

#36 [signup UI] add password instructions
  Frontend/frontend/src/components/Auth.js
  Frontend/frontend/src/index.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
